import py_cui

TRAILHEAD_SELECTED = py_cui.BLACK_ON_CYAN
ROUTE_SELECTED = py_cui.BLACK_ON_YELLOW
STAY_SELECTED = py_cui.BLACK_ON_WHITE

TRAILHEAD_DEFAULT = py_cui.CYAN_ON_BLACK
ROUTE_DEFAULT = py_cui.YELLOW_ON_BLACK
STAY_DEFAULT = py_cui.WHITE_ON_BLACK
